version: "3.8"

services:
  backend:
    build:
      context: "../backend"
      dockerfile: Dockerfile.dev
    environment:
      - CHROME_PATH=/usr/bin/google-chrome-stable
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - ENV=development
      - MONGODB_URI=mongodb://mongo:27017
    volumes: 
      - ../backend:/app
      - ../browserData:/app/browserData
    tmpfs:
      - /tmp/chrome-user-data
    depends_on:
      - mongo

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    volumes: 
      - ../frontend:/app
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:latest
    ports:
      - "22222:27017"
    volumes:          
      - ./mongo/db:/data/db
    command: mongod --bind_ip_all

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio:/data
    environment:
      MINIO_ROOT_USER: pradyut
      MINIO_ROOT_PASSWORD: pradyut2006
    command: server --console-address ":9001" /data

  nginx:
    image: nginx:latest
    ports:
      - "1000:80"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - minio

volumes:
  mongodb_data:
  node_modules:
